### ISSUE TITLE
Question about constraints A11

### ISSUE THREAD

**Issue by ChenxiH** [shepardyan/Resilient-Reconfiguration-Problem-for-Distribution-Systems#3]
Hi! In your implementation, I noticed the constraint for A11 is formulated as: delta <= epsilon ( row 133 in resilient_reconfiguration.m )
However, the original constraint in the paper usually appears as: delta >= epsilon
Is this a mistake or there are other reasons for that?

**Comment by shepardyan** [comment]
Firstly, I apologize for not responding in a timely manner and thank you for pointing out this issue. This involves a matter of understanding the modeling. In my understanding, a bus can be connected to other buses without carrying a load, meaning a bus is first energized, and then it is decided whether to pick up the load. The understanding in the article is to "enforce pick-up of the load once its located node is energized by power sources," which means that as long as a bus has a path to the power source, it must pick up the corresponding load on the bus. If the current system resources are insufficient to support a load, the corresponding bus cannot be connected to the system. Both interpretations have their own rationale. I will point this out in the documentation and discuss the differences between the two modeling approaches.

**Comment by ChenxiH** [comment]
Thanks for the reply! Actually I have the same concern with you. I think delta <= epsilon can also allow partial pick up and not just 0/1

**Comment by shepardyan** [comment]
Yes, in that case, I think we would need to relax $\delta_i$ to be a continuous variable. I will provide additional explanations for this part when I have time after PES GM. Thank you again for your interest in this repository.

**Comment by ChenxiH** [comment]
I am also as PES GM hhh
